version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard   
  enable:
    - staticcheck
    - govet
    - errcheck
    - revive
    - gocritic
    - gocognit
    - gocyclo
    - unparam
    - prealloc
    - depguard
    - dogsled
    - nolintlint
    - wastedassign
    - copyloopvar
    - lll
    - errname
    - errorlint
  disable:
    - dupl
    - funlen
    - testpackage

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/your-org/your-repo
  gocyclo:
    min-complexity: 15
  depguard:
    list-type: blacklist
    packages:
      - fmt
    packages-with-error-message:
      fmt: "use logger instead of fmt"
