# must be for backward compatibility.
version: "1"

# description types from cli for select correct builder, don't change it.
x-proxy-type:
  custom: &proxy-custom "custom" # if using cli waiting full custom template.
  logger: &proxy-logger "logger"
  tracer: &proxy-tracer "tracer"
  retrier: &proxy-retrier "retrier"

# description implementation types, don't change it.
x-proxy-implementation:
  custom-implementation: &proxy-implementation-custom "custom" # using this cli, a custom template is expected, and its size must be within the limits of the preset.
  zap-logger: &proxy-implementation-zap "zap"
  opentelemetry-tracer: &proxy-implementation-opentelemetry "opentelemetry"
  backoff-retrier: &proxy-implementation-backoff "backoff"

# turn off/on debug level for logger of cli.
debug: true

# proxy allow to turn off/on generating proxy layer.
proxy:
  - name: logger
    ptype: *proxy-logger
    itype: *proxy-implementation-zap
  - name: tracer
    ptype: *proxy-tracer
    itype: *proxy-implementation-opentelemetry
  - name: retrier
    ptype: *proxy-retrier
    itype: *proxy-implementation-backoff
  - name: debug_logger
    ptype: *proxy-logger
    itype: *proxy-implementation-custom
    path: ./logger.tmpl